### PR TITLE
Update and rename config.w32 to \config.w32

### PR DESCRIPTION
**Pull request by steventam312**

### CODE REVIEW

**Comment by kelunik** [comment]
Why that rename?

**Comment by lvht** [comment]
Actually this is a mistake~

**Comment by lvht** [comment]
@kelunik Should we revert this change?

**Comment by kelunik** [comment]
I only looked at that because of https://github.com/fiberphp/fiber-ext/commit/bf9ab9a235ada1eb40bf51cfbdca3359e7d129c6

I think so, yes.

**Comment by kelunik** [comment]
@lvht Not only the name is wrong, but the full commit is bogus.

**Comment by lvht** [comment]
@kelunik Sorry. This PR was merged accidentally, and reverted by 415433f094d1beca94b24038b5f07c7d11a2fe5b

**Comment by lvht** [comment]
Would you @steventam312 like to offer more detail about this PR?

**Pull request merged**
